# Generated by Django 5.1.3 on 2024-11-16 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('allergy_warning', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalFlavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('suggestion', models.TextField()),
                ('allergies', models.TextField(blank=True, null=True)),
                ('suggestion_date', models.DateField(auto_now_add=True)),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_name.seasonalflavour')),
            ],
        ),
    ]
